FROM node:20-alpine

RUN npm i -g pnpm

WORKDIR /var/www/html

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

# Change current user
# USER node

EXPOSE 5173
CMD [ "pnpm", "build" ]
